# Generated by Django 2.1.2 on 2018-12-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cenario',
                'verbose_name_plural': 'Cenarios',
            },
        ),
        migrations.CreateModel(
            name='FunciolidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
            },
        ),
        migrations.CreateModel(
            name='PlanoDeTesteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Manual', 'MANUAL'), ('Funcional Automatizado', 'FUNCIONAL AUTOMATIZADO'), ('Performance', 'PERFORMANCE'), ('Analise de Codigo', 'ANALISE DE CODIGO'), ('Teste de Penetração', 'TESTE DE PENETRAÇÃO'), ('Teste de API', 'TESTE DE API'), ('Segurança de Aplicação', 'SEGURANÇA DE APLICAÇÃO')], max_length=50)),
            ],
            options={
                'verbose_name': 'Plano de teste',
                'verbose_name_plural': 'Planos de testes',
            },
        ),
        migrations.CreateModel(
            name='ProjetoTesteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Projeto de teste',
                'verbose_name_plural': 'Projetos de testes',
            },
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('Dado', 'DADO'), ('Quando', 'QUANDO'), ('Entao', 'ENTAO'), ('E', 'E')], max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('actions', models.TextField()),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.AddField(
            model_name='planodetestemodel',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Front_Api.ProjetoTesteModel'),
        ),
        migrations.AddField(
            model_name='funciolidademodel',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Front_Api.PlanoDeTesteModel'),
        ),
        migrations.AddField(
            model_name='cenariomodel',
            name='funcionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Front_Api.FunciolidadeModel'),
        ),
        migrations.AddField(
            model_name='cenariomodel',
            name='steps',
            field=models.ManyToManyField(to='Front_Api.StepModel'),
        ),
    ]
